Repository dfds/terraform-aws-rds, pull requests merged in 2024-02, with the labels that each got.

#96 ip whitelist vars documentation
  README.md
  variables.tf
Labels: release:patch

#98 Add another period symbol
  README.md
  variables.tf
Labels: release:patch

#100 backup retention minor update
  locals.tf
  main.tf
Labels: release:patch

#101 Feature/enable default cw exports on prod
  .github/CODEOWNERS
  README.md
  locals.tf
  main.tf
  variables.tf
Labels: release:minor

#103 Configure renovate to add labels automatically
  .github/CODEOWNERS
  renovate.json
Labels: norelease

#104 Replace tfsec with trivy
  .github/workflows/tfsec.yml
  .github/workflows/trivy.yml
Labels: norelease

#95 Update dependency black to v24
  scripts/qa/poetry.lock
  scripts/qa/pyproject.toml
Labels: norelease

#68 Update dependency pandas to v2.2.0
  scripts/qa/poetry.lock
Labels: norelease

#69 Update dependency pylint to v3.0.3
  scripts/qa/poetry.lock
Labels: norelease

#70 Update dependency sqlalchemy to v2.0.27
  scripts/qa/poetry.lock
Labels: norelease

#72 Update dependency boto3 to v1.34.47
  scripts/qa/poetry.lock
Labels: norelease

#73 Update actions/checkout action to v4
  .github/workflows/documentation.yml
  .github/workflows/secret-detection.yml
Labels: norelease

#74 Update dependency flake8 to v7
  scripts/qa/poetry.lock
  scripts/qa/pyproject.toml
Labels: norelease

#106 Update dependency pandas to v2.2.1
  scripts/qa/poetry.lock
Labels: release:patch

#107 Update dependency boto3 to v1.34.51
  scripts/qa/poetry.lock
Labels: release:patch

#109 Add norelease label to pull requests on the QA folder Run QA automatically on changes to QA folder
  .github/workflows/qa.yml
  renovate.json
Labels: norelease

#110 Dummy PR to test QA automation
  tests/qa/main.tf
Labels: norelease

#111 Fix typos in two pipelines
  .github/workflows/auto-release.yml
  .github/workflows/qa.yml
Labels: norelease

#112 Dummy PR to test QA on merge
  tests/qa/main.tf
Labels: norelease

#114 Update dependency boto3 to v1.34.52
  scripts/qa/poetry.lock
Labels: release:patch
