Repository dfds/terraform-aws-rds, pull requests merged in 2024-01, with the labels that each got.

#64 Minor thing - missing "/" for output location in README.md docker command.
  tools/README.md
Labels: documentation, norelease

#65 Fix repo URL in scaffolding template
  tools/scaffolding/templates/main.tf.template
Labels: release:patch

#60 Refactor test and examples. SG rule for vpc peering setup improved
  README.md
  data.tf
  examples/multi_az_cluster/main.tf
  examples/shared/vpc.tf
  examples/single_instance/main.tf
  examples/single_instance_k8s/main.tf
  locals.tf
  main.tf
  tests/instance/main.tf
  tests/multi_az_cluster/main.tf
  tests/serverless/main.tf
  tools/README.md
  variables.tf
Labels: release:patch

#66 Configure Renovate
  renovate.json
Labels: enhancement, norelease

#76 Fix bug with outputs in scaffolding and improve scaffolding documentation
  tools/Dockerfile
  tools/README.md
  tools/scaffolding/scripts/generate_tf_module.py
Labels: release:minor

#67 Feat/add blueprints tag
  locals.tf
Labels: release:minor

#77 Add workflow for creating releases on merge to primary branch
  .github/workflows/auto-release.yml
Labels: norelease

#78 Fix block-on-hold-prs github action
  .github/workflows/block-on-hold-prs.yml
Labels: norelease

#75 automation_initiator_location set by user
  README.md
  locals.tf
  tests/qa/main.tf
  tools/scaffolding/templates/main.tf.template
  variables.tf
Labels: release:patch

#80 Add github action
  .github/workflows/trigger-blueprints-repo.yaml
Labels: norelease

#81 Update trigger-blueprints-repo.yaml
  .github/workflows/trigger-blueprints-repo.yaml
Labels: norelease

#82 Add example for list of subnet to description
  README.md
  variables.tf
Labels: release:patch

#84 licensing driven tf version restriction
  README.md
  outputs.tf
  versions.tf
Labels: release:patch

#86 Remove tools folder
  tools/Dockerfile
  tools/README.md
  tools/scaffolding/scripts/entrypoint.sh
  tools/scaffolding/scripts/generate_docker.py
  tools/scaffolding/scripts/generate_tf_module.py
  tools/scaffolding/templates/.env.template
  tools/scaffolding/templates/compose.yml.template
  tools/scaffolding/templates/main.tf.template
  tools/scaffolding/templates/pipeline.yml.template
  tools/scaffolding/templates/restore.sh.template
Labels: release:patch

#87 Update trigger-blueprints-repo.yaml
  .github/workflows/trigger-blueprints-repo.yaml
Labels: release:patch

#88 Update variables.tf
  README.md
  variables.tf
Labels: release:patch

#89 Avoid duplicate releases
  .github/workflows/qa.yml
Labels: norelease

#92 Trigger a release
  README.md
  variables.tf
Labels: release:patch

#93 Move dispatch to auto-release
  .github/workflows/auto-release.yml
  .github/workflows/trigger-blueprints-repo.yaml
  modules/cloudwatch_log_groups/variables.tf
Labels: release:patch
