Repository dfds/terraform-aws-rds, pull requests merged in 2024-03, with the labels that each got.

#116 Update dependency boto3 to v1.34.54
  scripts/qa/poetry.lock
Labels: release:patch

#118 Update dependency boto3 to v1.34.55
  scripts/qa/poetry.lock
Labels: release:patch

#117 Update dependency sqlalchemy to v2.0.28
  scripts/qa/poetry.lock
Labels: release:patch

#119 Update dependency boto3 to v1.34.56
  scripts/qa/poetry.lock
Labels: release:patch

#120 Update dependency boto3 to v1.34.57
  scripts/qa/poetry.lock
Labels: release:patch

#122 Update dependency boto3 to v1.34.58
  scripts/qa/poetry.lock
Labels: release:patch

#123 Update dependency boto3 to v1.34.59
  scripts/qa/poetry.lock
Labels: release:patch

#125 Update dependency boto3 to v1.34.61
  scripts/qa/poetry.lock
Labels: release:patch

#126 Update dependency boto3 to v1.34.62
  scripts/qa/poetry.lock
Labels: release:patch

#127 Update dependency boto3 to v1.34.64
  scripts/qa/poetry.lock
Labels: release:patch

#129 feat: allow appending additional security groups
  README.md
  main.tf
  variables.tf
Labels: release:minor

#130 chore(deps): update dependency boto3 to v1.34.69
  scripts/qa/poetry.lock
Labels: release:patch

#132 chore(deps): update dependency sqlalchemy to v2.0.29
  scripts/qa/poetry.lock
Labels: release:patch

#131 fix: specify type for the additional rds security groups
  README.md
  variables.tf
Labels: release:patch

#133 change type for triggering blueprint workflow
  .github/workflows/auto-release.yml
Labels: norelease

#134 chore(deps): update dependency boto3 to v1.34.70
  scripts/qa/poetry.lock
Labels: release:patch

#135 chore(deps): update dependency boto3 to v1.34.71
  scripts/qa/poetry.lock
Labels: release:patch
