Repository dfds/terraform-aws-rds, pull requests merged in 2025-01, with the labels that each got.

#252 fix(deps): update dependency boto3 to v1.35.90
  scripts/qa/poetry.lock
Labels: release:patch

#253 fix(deps): update dependency boto3 to v1.35.94
  scripts/qa/poetry.lock
Labels: release:patch

#255 fix(deps): update dependency sqlalchemy to v2.0.37
  scripts/qa/poetry.lock
Labels: release:patch

#254 fix(deps): update dependency boto3 to v1.35.99
  scripts/qa/poetry.lock
Labels: release:patch

#256 fix(deps): update dependency boto3 to v1.36.3
  scripts/qa/poetry.lock
Labels: release:patch

#259 chore(deps): update dependency black to v25
  scripts/qa/poetry.lock
  scripts/qa/pyproject.toml
Labels: release:major

#258 fix(deps): update dependency pylint to v3.3.4
  scripts/qa/poetry.lock
Labels: release:patch

#257 fix(deps): update dependency boto3 to v1.36.8
  scripts/qa/poetry.lock
Labels: release:patch

#260 Update renovate.json
  renovate.json
Labels: norelease
